[package]
name = "winty"
description = "Easy way to create windows"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[features]
default = ["x11"]
x11 = ["winty-x11"]

[dependencies]
winty-x11 = { path = "./winty-x11", optional = true }
winty-core = { path = "./winty-core" }
winty-dpi = { path = "./winty-dpi" }
thiserror = "2.0.12"

[workspace]
members = [ "winty-core", "winty-dpi", "winty-example", "winty-gl", "winty-x11" ]

